security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        api:
            pattern: ^/api
            stateless: true
            entry_point: jwt
            json_login:
                check_path: /api/users/token/login
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
            refresh_jwt:
                check_path: /api/users/token/refresh
            logout:
                path: /api/users/token/invalidate


    access_control:
        - { path: ^/api/doc,                      roles: PUBLIC_ACCESS }
        - { path: ^/api/users/token/login,        roles: PUBLIC_ACCESS }
        - { path: ^/api/users/register,           roles: PUBLIC_ACCESS  }
        - { path: ^/api,                          roles: IS_AUTHENTICATED_FULLY }